### PR TITLE
fix: env variable is too long

### PR DESCRIPTION
**Pull request by v1v**
breaking change

# Pull Request Title [Delete this and put your own]

- [ ] Check this box.

## What this PR is about

Remove env variable that cannot be that long.

Closes https://github.com/JJ/github-pr-contains-action/issues/119

### CODE REVIEW

**Comment by JJ** [comment]
OK, I get what you're trying to do here, but it's a breaking change so we have to take it in stride. If possible, I would like to see an issue that explains what's happening to see if we can come up with a better solution; if you can't; or won't, do that, I would rather have the variable value substituted by an invalid string, pointing it to other ways of obtaining the same value.

**Comment by v1v** [comment]
I added some details in https://github.com/JJ/github-pr-contains-action/issues/119#issuecomment-1946138011

**Review by JJ — APPROVED** [review]
Also helps #121

**Comment by JJ** [comment]
Thanks! It will go in the next release, available soonish.

**Pull request merged**
